import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { randomUUID } from "node:crypto";
import { homedir } from "node:os";
import path from "node:path";
import { runLensSwarm, loadProjectContext } from "./orchestrate.js";
import { resolveLenses } from "./lenses.js";

const SWEEP_DIR = path.join(homedir(), ".local", "share", "opencode-mcp", "sweeps");

// Cooperative cancellation: there was previously NO way to stop a running
// sweep short of killing the whole MCP server process (which takes the tool
// down for the entire session) — observed 2026-08-22 needing exactly that
// after a sweep at replicas:4 ran 5h42m without a single segment completing
// successfully. `isSweepCancelled` is checked both between segments and
// inside each segment's concurrency-limited dispatch (see
// `mapWithConcurrency`'s `isCancelled` param in orchestrate.js), so a cancel
// request stops handing out new work promptly rather than only at the next
// segment boundary — worst case it still finishes whatever's already
// in-flight for the current wave (bounded by `maxConcurrency`).
const cancelledSweeps = new Set();
export function requestSweepCancel(sweepId) {
  cancelledSweeps.add(sweepId);
}
export function isSweepCancelled(sweepId) {
  return cancelledSweeps.has(sweepId);
}

/** Rough chars-per-token, same convention used elsewhere in this repo. */
const CHARS_PER_TOKEN = 4;
const DEFAULT_SEGMENT_TOKENS = 40_000;

/**
 * Language-agnostic defaults. Deliberately NOT tuned to one ecosystem — the
 * Dart-specific patterns that motivated this (`*.g.dart`, `*.freezed.dart`)
 * are covered by the generic `*.g.*` / `*.freezed.*` forms, and anything a
 * project needs beyond this is the caller's job via `excludeGlobs`.
 */
const DEFAULT_EXCLUDE_GLOBS = [
  "**/node_modules/**", "**/vendor/**", "**/third_party/**", "**/.git/**",
  "**/dist/**", "**/build/**", "**/out/**", "**/target/**", "**/bin/**", "**/obj/**",
  "**/.next/**", "**/.nuxt/**", "**/.dart_tool/**", "**/.venv/**", "**/venv/**",
  "**/__pycache__/**", "**/Pods/**", "**/coverage/**", "**/__snapshots__/**",
  "**/*.min.*", "**/*.bundle.*", "**/*.map",
  "**/*.g.*", "**/*.freezed.*", "**/*.pb.*", "**/*_pb2.*", "**/*.generated.*", "**/*.designer.*",
  "**/*.lock", "**/*-lock.json", "**/*.sum",
  "**/package-lock.json", "**/yarn.lock", "**/pnpm-lock.yaml", "**/Gemfile.lock", "**/poetry.lock", "**/composer.lock",
];

/** Extensions treated as reviewable source. Overridable via `sourceExtensions`. */
const DEFAULT_SOURCE_EXTENSIONS = [
  ".js", ".jsx", ".mjs", ".cjs", ".ts", ".tsx", ".dart", ".py", ".rb", ".go", ".rs",
  ".java", ".kt", ".kts", ".swift", ".m", ".mm", ".c", ".h", ".cc", ".cpp", ".hpp",
  ".cs", ".php", ".scala", ".ex", ".exs", ".sh", ".bash", ".sql", ".vue", ".svelte",
];

/**
 * Markers that identify machine-generated files regardless of language.
 * Globs miss plenty of generated code (a hand-named file produced by a
 * codegen step); the header almost always says so. Only the first chunk of
 * the file is scanned.
 */
const GENERATED_MARKERS = [
  "@generated",
  "GENERATED CODE - DO NOT MODIFY",
  "GENERATED FILE - DO NOT EDIT",
  "Code generated by",
  "This file was automatically generated",
  "DO NOT EDIT THIS FILE",
  "AUTO-GENERATED",
  "autogenerated by",
];
const GENERATED_SNIFF_BYTES = 800;

/** Minimal glob matcher: supports `**`, `*` and `?`. Enough for path filters, no dependency needed. */
function globToRegExp(glob) {
  let re = "";
  for (let i = 0; i < glob.length; i++) {
    const c = glob[i];
    if (c === "*") {
      if (glob[i + 1] === "*") {
        re += ".*";
        i++;
        if (glob[i + 1] === "/") i++;
      } else {
        re += "[^/]*";
      }
    } else if (c === "?") re += "[^/]";
    else re += c.replace(/[.+^${}()|[\]\\]/g, "\\$&");
  }
  return new RegExp(`^${re}$`);
}

function matchesAny(filePath, globs) {
  return globs.some((g) => globToRegExp(g).test(filePath));
}

function looksGenerated(absPath) {
  try {
    const fd = readFileSync(absPath, "utf8").slice(0, GENERATED_SNIFF_BYTES);
    const upper = fd.toUpperCase();
    return GENERATED_MARKERS.some((m) => upper.includes(m.toUpperCase()));
  } catch {
    return false;
  }
}

/**
 * Enumerate reviewable source files: everything git tracks (plus untracked
 * files that aren't gitignored), minus excluded globs, minus non-source
 * extensions, minus anything whose header says it's generated.
 *
 * Returns both the kept files and a breakdown of what was dropped and why —
 * a sweep that silently skipped half the repo would be worse than useless,
 * and the caller needs this to correct its filters (see `plan` mode).
 */
export function discoverFiles({ dir, includeGlobs, excludeGlobs, sourceExtensions, skipGeneratedSniff = false }) {
  const cwd = dir || process.cwd();
  const listed = execFileSync("git", ["ls-files", "--cached", "--others", "--exclude-standard"], {
    cwd,
    maxBuffer: 50 * 1024 * 1024,
  })
    .toString("utf8")
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);

  const exts = (sourceExtensions && sourceExtensions.length ? sourceExtensions : DEFAULT_SOURCE_EXTENSIONS).map((e) =>
    e.startsWith(".") ? e.toLowerCase() : `.${e.toLowerCase()}`
  );
  const excludes = [...DEFAULT_EXCLUDE_GLOBS, ...(excludeGlobs || [])];
  const includes = includeGlobs && includeGlobs.length ? includeGlobs : null;

  const kept = [];
  const skipped = { notSource: 0, excluded: 0, notIncluded: 0, generated: 0, unreadable: 0 };
  const generatedFiles = [];

  for (const rel of listed) {
    if (includes && !matchesAny(rel, includes)) {
      skipped.notIncluded++;
      continue;
    }
    if (!exts.includes(path.extname(rel).toLowerCase())) {
      skipped.notSource++;
      continue;
    }
    if (matchesAny(rel, excludes)) {
      skipped.excluded++;
      continue;
    }
    const abs = path.join(cwd, rel);
    let size;
    try {
      size = statSync(abs).size;
    } catch {
      skipped.unreadable++;
      continue;
    }
    if (!skipGeneratedSniff && looksGenerated(abs)) {
      skipped.generated++;
      generatedFiles.push(rel);
      continue;
    }
    kept.push({ path: rel, bytes: size, approxTokens: Math.ceil(size / CHARS_PER_TOKEN) });
  }

  kept.sort((a, b) => a.path.localeCompare(b.path));
  return { files: kept, skipped, generatedFiles, totalListed: listed.length };
}

/**
 * Pack files into review segments under a token budget.
 *
 * Sorted by PATH, not by size: keeping a directory together means one segment
 * sees a feature's files as a unit, which is where the cross-file findings
 * live (a caller and callee disagreeing, two symmetric paths updated
 * inconsistently). Bin-packing by size would scatter related code across
 * segments and lose exactly those.
 *
 * A single file over budget gets its own segment rather than being split
 * mid-function.
 */
export function planSegments(files, budgetTokens = DEFAULT_SEGMENT_TOKENS) {
  const segments = [];
  let current = { files: [], approxTokens: 0 };
  for (const f of files) {
    if (f.approxTokens >= budgetTokens) {
      if (current.files.length) {
        segments.push(current);
        current = { files: [], approxTokens: 0 };
      }
      segments.push({ files: [f], approxTokens: f.approxTokens, oversized: true });
      continue;
    }
    if (current.approxTokens + f.approxTokens > budgetTokens && current.files.length) {
      segments.push(current);
      current = { files: [], approxTokens: 0 };
    }
    current.files.push(f);
    current.approxTokens += f.approxTokens;
  }
  if (current.files.length) segments.push(current);
  return segments.map((s, i) => ({ index: i, ...s }));
}

function sweepPath(id, ext = "json") {
  return path.join(SWEEP_DIR, `${id}.${ext}`);
}

function persistSweep(state) {
  try {
    mkdirSync(SWEEP_DIR, { recursive: true });
    writeFileSync(sweepPath(state.sweepId), JSON.stringify(state, null, 2));
  } catch (e) {
    console.error("[opencode-mcp] failed to persist sweep state:", e.message ?? e);
  }
}

export function loadSweep(id) {
  const p = sweepPath(id);
  if (!existsSync(p)) return null;
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return null;
  }
}

export function listSweeps() {
  try {
    if (!existsSync(SWEEP_DIR)) return [];
    return readdirSync(SWEEP_DIR)
      .filter((f) => f.endsWith(".json"))
      .map((f) => loadSweep(f.replace(/\.json$/, "")))
      .filter(Boolean)
      .map((s) => ({
        sweepId: s.sweepId,
        dir: s.dir,
        status: s.status,
        completedSegments: s.completedSegments,
        totalSegments: s.totalSegments,
        confirmedFindings: s.ledger?.length ?? 0,
        startedAt: s.startedAt,
        finishedAt: s.finishedAt,
        reportPath: s.reportPath,
      }))
      .sort((a, b) => (b.startedAt ?? 0) - (a.startedAt ?? 0));
  } catch {
    return [];
  }
}

/** Build the human-facing markdown report deterministically — no extra LLM call, so it can't hallucinate a summary. */
function buildReport(state) {
  const lines = [];
  lines.push(`# Whole-project QA sweep`);
  lines.push("");
  lines.push(`- **Repo:** \`${state.dir}\``);
  lines.push(`- **Sweep id:** \`${state.sweepId}\``);
  lines.push(`- **Status:** ${state.status}`);
  lines.push(`- **Segments:** ${state.completedSegments}/${state.totalSegments}`);
  lines.push(`- **Files reviewed:** ${state.fileCount}`);
  lines.push(`- **Lenses:** ${state.lensKeys.join(", ")} (${state.replicas} reviewers each, depth ${state.depth})`);
  if (state.projectContextFile) lines.push(`- **Project context:** \`${state.projectContextFile}\``);
  lines.push(`- **Started:** ${new Date(state.startedAt).toISOString()}`);
  if (state.finishedAt) lines.push(`- **Finished:** ${new Date(state.finishedAt).toISOString()}`);
  const totalTokens = state.segments.reduce((a, s) => a + (s.tokens?.input ?? 0) + (s.tokens?.output ?? 0), 0);
  lines.push(`- **Tokens spent:** ~${totalTokens.toLocaleString()}`);
  lines.push("");

  const bySeverity = { high: [], medium: [], low: [] };
  for (const f of state.ledger) (bySeverity[f.severity] ?? bySeverity.medium).push(f);

  lines.push(`## Confirmed findings (${state.ledger.length})`);
  lines.push("");
  if (!state.ledger.length) {
    lines.push("_No findings survived corroboration and adversarial review._");
    lines.push("");
  } else {
    for (const sev of ["high", "medium", "low"]) {
      if (!bySeverity[sev].length) continue;
      lines.push(`### ${sev.toUpperCase()} (${bySeverity[sev].length})`);
      lines.push("");
      for (const f of bySeverity[sev]) {
        lines.push(`- **${f.location}** — ${f.title}  \n  _lens: ${f.lens} · segment ${f.segmentIndex + 1}_`);
      }
      lines.push("");
    }
  }

  lines.push(`## Per-segment reports`);
  lines.push("");
  for (const seg of state.segments) {
    lines.push(`### Segment ${seg.index + 1}/${state.totalSegments} — ${seg.status}`);
    lines.push("");
    lines.push(`<details><summary>${seg.files.length} file(s), ~${seg.approxTokens.toLocaleString()} tokens</summary>`);
    lines.push("");
    for (const f of seg.files) lines.push(`- \`${f}\``);
    lines.push("");
    lines.push(`</details>`);
    lines.push("");
    lines.push(seg.report || `_${seg.error ? `Failed: ${seg.error}` : "No report produced."}_`);
    lines.push("");
  }
  return lines.join("\n");
}

function writeReport(state) {
  try {
    mkdirSync(SWEEP_DIR, { recursive: true });
    const p = sweepPath(state.sweepId, "md");
    writeFileSync(p, buildReport(state));
    return p;
  } catch (e) {
    console.error("[opencode-mcp] failed to write sweep report:", e.message ?? e);
    return null;
  }
}

/** Inline a segment's files, hard-capped so one pathological file can't blow the prompt. */
function readSegmentContent(dir, files, budgetTokens) {
  const cap = budgetTokens * CHARS_PER_TOKEN * 1.2;
  const parts = [];
  let used = 0;
  for (const f of files) {
    let body;
    try {
      body = readFileSync(path.join(dir, f.path), "utf8");
    } catch (e) {
      parts.push(`--- ${f.path} ---\n[unreadable: ${e.message ?? e}]`);
      continue;
    }
    if (used + body.length > cap) {
      const room = Math.max(0, cap - used);
      parts.push(`--- ${f.path} (TRUNCATED — open it yourself if your lens needs the rest) ---\n${body.slice(0, room)}`);
      used = cap;
      continue;
    }
    parts.push(`--- ${f.path} ---\n${body}`);
    used += body.length;
  }
  return parts.join("\n\n");
}

/**
 * Whole-project sweep: segment the repo, run the lens swarm over each segment
 * in turn, and accumulate confirmed findings into a ledger that is fed into
 * every later segment (so reviewers stop re-reporting known bugs and start
 * hunting for other instances of the same class).
 *
 * Runs SEQUENTIALLY by segment on purpose: the whole value of the ledger is
 * that segment N+1 knows what segment N confirmed, which parallel segments
 * would lose. Expect this to take a long time — that's why it's checkpointed
 * to disk after every segment and driven through start/poll rather than one
 * blocking call.
 */
export async function runSweep(opts) {
  const {
    dir,
    lenses: lensSelection,
    replicas,
    depth = 1,
    groupSize,
    maxConcurrency,
    budgetTokens = DEFAULT_SEGMENT_TOKENS,
    includeGlobs,
    excludeGlobs,
    sourceExtensions,
    skipGeneratedSniff,
    maxSegments,
    contextFile,
    focus,
    model,
    variant,
    tier,
    waitMs,
    onUpdate,
  } = opts;

  const cwd = dir || process.cwd();
  const { lenses, unknown } = resolveLenses(lensSelection);
  const projectContext = loadProjectContext({ dir: cwd, contextFile });
  const discovery = discoverFiles({ dir: cwd, includeGlobs, excludeGlobs, sourceExtensions, skipGeneratedSniff });
  let segments = planSegments(discovery.files, budgetTokens);
  let segmentsDropped = 0;
  if (Number.isInteger(maxSegments) && maxSegments > 0 && segments.length > maxSegments) {
    segmentsDropped = segments.length - maxSegments;
    segments = segments.slice(0, maxSegments);
  }

  const state = {
    sweepId: opts.sweepId ?? randomUUID(),
    dir: cwd,
    status: "running",
    startedAt: Date.now(),
    finishedAt: null,
    lensKeys: lenses.map((l) => l.key),
    unknownLenses: unknown,
    replicas: replicas ?? 2,
    depth,
    budgetTokens,
    projectContextFile: projectContext?.path ?? null,
    fileCount: discovery.files.length,
    discovery: { skipped: discovery.skipped, totalListed: discovery.totalListed, generatedSample: discovery.generatedFiles.slice(0, 20) },
    totalSegments: segments.length,
    segmentsDropped,
    completedSegments: 0,
    segments: segments.map((s) => ({
      index: s.index,
      files: s.files.map((f) => f.path),
      approxTokens: s.approxTokens,
      oversized: Boolean(s.oversized),
      status: "pending",
      report: null,
      findings: [],
      error: null,
      tokens: null,
    })),
    ledger: [],
    refutedLedger: [],
    reportPath: null,
    error: null,
  };
  persistSweep(state);
  onUpdate?.(state);

  try {
    for (const seg of segments) {
      if (isSweepCancelled(state.sweepId)) {
        state.status = "cancelled";
        console.error(`[opencode-mcp] sweep ${state.sweepId}: cancellation requested, stopping before segment ${seg.index + 1}/${segments.length}.`);
        break;
      }

      const entry = state.segments[seg.index];
      entry.status = "running";
      entry.startedAt = Date.now();
      persistSweep(state);

      const content = readSegmentContent(cwd, seg.files, budgetTokens);
      const fileList = seg.files.map((f) => `- ${f.path}`).join("\n");
      const scopeLabel =
        `one sector of a larger codebase — segment ${seg.index + 1} of ${segments.length}. Your assigned sector is these files:\n${fileList}`;

      try {
        const { reconciliation } = await runLensSwarm({
          scopeLabel,
          contentSection: `CONTENTS OF YOUR ASSIGNED SECTOR:\n\n${content}`,
          contentSummaryForAggregator: `The reviewed sector was: ${seg.files.map((f) => f.path).join(", ")}`,
          lenses,
          replicas,
          depth,
          groupSize,
          maxConcurrency,
          isCancelled: () => isSweepCancelled(state.sweepId),
          dir: cwd,
          model,
          variant,
          tier,
          waitMs,
          focus,
          projectContext,
          knownFindings: state.ledger,
          refutedFindings: state.refutedLedger,
          titlePrefix: `mcp-sweep-s${seg.index + 1}`,
          emitFindingsBlock: true,
          roamHint:
            `Your assigned sector is a STARTING POINT, not a boundary. You have read-only access to the entire repository — ` +
            `follow any flow wherever it goes (callers, callees, shared helpers, tests, config) whenever tracing it end-to-end ` +
            `is what your lens actually requires. Report defects in your assigned files primarily; if tracing leads you to a ` +
            `genuine defect in a file outside the sector, report it too and say explicitly that it is outside your sector.`,
        });

        // A reconciliation that timed out mid-way returns `incomplete` with an
        // empty report. Marking that segment "completed" with zero findings
        // would be indistinguishable from a genuinely clean segment — the one
        // outcome this whole pipeline must never produce silently.
        entry.status = reconciliation?.incomplete ? "incomplete" : "completed";
        if (reconciliation?.incomplete) {
          entry.error =
            `Reconciliation did not finish (final aggregation status: ${reconciliation.finalJob?.status ?? "unknown"}` +
            `${reconciliation.finalJob?.errorMessage ? `, ${reconciliation.finalJob.errorMessage}` : ""}). ` +
            `Most often this is waitMs being too short for an aggregator digesting every participant's findings — raise waitMs, or lower replicas/lenses so there is less to digest.`;
          console.error(`[opencode-mcp] sweep segment ${seg.index + 1}: ${entry.error}`);
        }
        entry.report = reconciliation?.report ?? null;
        entry.findings = reconciliation?.findings ?? [];
        entry.tokens = reconciliation?.finalJob?.tokens ?? null;
        entry.refuted = reconciliation?.refuted ?? [];
        for (const f of entry.findings) state.ledger.push({ ...f, segmentIndex: seg.index });
        for (const r of entry.refuted) state.refutedLedger.push({ ...r, segmentIndex: seg.index });
      } catch (e) {
        entry.status = "failed";
        entry.error = String(e.message ?? e);
        console.error(`[opencode-mcp] sweep segment ${seg.index + 1} failed:`, entry.error);
      }

      entry.finishedAt = Date.now();
      state.completedSegments++;
      state.reportPath = writeReport(state);
      persistSweep(state);
      onUpdate?.(state);
    }
    if (state.status !== "cancelled") state.status = "completed";
  } catch (e) {
    state.status = "failed";
    state.error = String(e.message ?? e);
  }

  cancelledSweeps.delete(state.sweepId);
  state.finishedAt = Date.now();
  state.reportPath = writeReport(state);
  persistSweep(state);
  onUpdate?.(state);
  return state;
}

/** Cheap dry run: what WOULD be reviewed, how it splits, and a rough time estimate — before committing an hour. */
export function planSweep(opts) {
  const cwd = opts.dir || process.cwd();
  const { lenses, unknown } = resolveLenses(opts.lenses);
  const budgetTokens = opts.budgetTokens ?? DEFAULT_SEGMENT_TOKENS;
  const discovery = discoverFiles({
    dir: cwd,
    includeGlobs: opts.includeGlobs,
    excludeGlobs: opts.excludeGlobs,
    sourceExtensions: opts.sourceExtensions,
    skipGeneratedSniff: opts.skipGeneratedSniff,
  });
  const segments = planSegments(discovery.files, budgetTokens);
  const replicas = Math.max(2, opts.replicas ?? 2);
  const depthVal = opts.depth ?? 1;
  const groupSize = Math.max(2, opts.groupSize ?? 4); // must match orchestrate.js's DEFAULT_GROUP_SIZE
  const participantCount = lenses.length * replicas;
  // Aggregator calls to reduce N leaves with branching factor `groupSize` in a
  // balanced tree = ceil((N-1)/(groupSize-1)) — one such reduction for the
  // round-0 aggregation, and one more per adversarial depth round.
  const treeCallsPerReduction = participantCount > 1 ? Math.ceil((participantCount - 1) / (groupSize - 1)) : 1;
  const perSegmentJobs = participantCount * (1 + depthVal) + (1 + depthVal) * treeCallsPerReduction;
  return {
    dir: cwd,
    lenses: lenses.map((l) => l.key),
    unknownLenses: unknown,
    replicas,
    depth: depthVal,
    groupSize,
    budgetTokens,
    projectContextFile: loadProjectContext({ dir: cwd, contextFile: opts.contextFile })?.path ?? null,
    fileCount: discovery.files.length,
    totalApproxTokens: discovery.files.reduce((a, f) => a + f.approxTokens, 0),
    segmentCount: segments.length,
    estimatedJobs: segments.length * perSegmentJobs,
    skipped: discovery.skipped,
    generatedSample: discovery.generatedFiles.slice(0, 20),
    // Per-segment file PATHS are omitted by default — observed 2026-08-22, a
    // 3,126-file/138-segment repo turned this into a 234,000-character
    // response, when the useful part of a plan is the ~15 summary fields
    // above. Pass `verbose: true` to get every segment's exact file list
    // back (e.g. to confirm one segment's membership after tuning filters);
    // otherwise use `fileSample` on a handful of segments as a spot check.
    segments: segments.map((s) => ({
      index: s.index,
      fileCount: s.files.length,
      approxTokens: s.approxTokens,
      oversized: Boolean(s.oversized),
      ...(opts.verbose ? { files: s.files.map((f) => f.path) } : { fileSample: s.files.slice(0, 3).map((f) => f.path) }),
    })),
  };
}
